export const TOGGLE_NAV = 'TOGGLE_NAV';
export const START_COUNTDOWN = 'START_COUNTDOWN';
export const SCROLL_POSITION = 'SCROLL_POSITION';
export const SET_NAV_COLOR = 'SET_NAV_COLOR';
export const OPEN_MODAL = 'OPEN_MODAL';
